services: 
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"  
    volumes:
      - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount NGINX config
    secrets:
      - nginx_crt
      - nginx_key
    restart: always

  wordpress:
    build:
      context: ./requirements/WordPress
    container_name: wordpress
    expose:
      - "9000"
    restart: always
    env_file:
      - ../secrets/.env

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    #image: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ../secrets/.env

secrets:
  nginx_crt:
    file: ../secrets/nginx/nginx.crt
  nginx_key:
    file: ../secrets/nginx/nginx.key
  wordpress_db_host:
    file: ../secrets/.env/db_hos