version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_network
    volumes:
      - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf
    secrets:
      - nginx_crt
      - nginx_key
    restart: always

  wordpress:
    build:
      context: ./requirements/WordPress
    container_name: wordpress
    expose:
      - "9000"
    restart: always
    env_file:
      - .env
    networks:
      - wp_network

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    networks:
      - wp_network

secrets:
  nginx_crt:
    file: ../secrets/nginx/nginx.crt
  nginx_key:
    file: ../secrets/nginx/nginx.key

networks:
  wp_network:
    name: wp_network
