version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_network
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress-data:/var/www/html
    restart: always

  wordpress:
    build:
      context: ./requirements/WordPress
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress-data:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - wp_network

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    networks:
      - wp_network

networks:
  wp_network:
    name: wp_network

volumes:
  wordpress-data:
