services: 
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"  
    volumes:
      - ./requirements/nginx/html:/usr/share/nginx/html  # Mount HTML content
      - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount NGINX config
    secrets:
      - nginx_crt
      - nginx_key
    restart: always

secrets:
  nginx_crt:
    file: ../secrets/nginx/nginx.crt
  nginx_key:
    file: ../secrets/nginx/nginx.key